/**
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import es.udima.tfm.cesarlaso.IotDslRuntimeModule;
import es.udima.tfm.cesarlaso.IotDslStandaloneSetup;
import es.udima.tfm.cesarlaso.ide.IotDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class IotDslIdeSetup extends IotDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    IotDslRuntimeModule _iotDslRuntimeModule = new IotDslRuntimeModule();
    IotDslIdeModule _iotDslIdeModule = new IotDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_iotDslRuntimeModule, _iotDslIdeModule));
  }
}
