/**
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.ide;

import es.udima.tfm.cesarlaso.ide.AbstractIotDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IotDslIdeModule extends AbstractIotDslIdeModule {
}
