/*
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IotDslStandaloneSetup extends IotDslStandaloneSetupGenerated {

	def static void doSetup() {
		new IotDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
