/**
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.ui.contentassist;

import es.udima.tfm.cesarlaso.ui.contentassist.AbstractIotDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class IotDslProposalProvider extends AbstractIotDslProposalProvider {
}
