/**
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso;

import es.udima.tfm.cesarlaso.IotDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotDslStandaloneSetup extends IotDslStandaloneSetupGenerated {
  public static void doSetup() {
    new IotDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
