/**
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso;

import es.udima.tfm.cesarlaso.AbstractIotDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotDslRuntimeModule extends AbstractIotDslRuntimeModule {
}
