/**
 */
package es.udima.cesarlaso.tfm.gpiosevents.provider;

import es.udima.cesarlaso.tfm.gpiosevents.util.GpioseventsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class GpioseventsItemProviderAdapterFactory extends GpioseventsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GpioseventsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosevents.Interrupted} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterruptedItemProvider interruptedItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosevents.Interrupted}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterruptedAdapter() {
		if (interruptedItemProvider == null) {
			interruptedItemProvider = new InterruptedItemProvider(this);
		}

		return interruptedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosevents.ButtonInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonInputItemProvider buttonInputItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosevents.ButtonInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonInputAdapter() {
		if (buttonInputItemProvider == null) {
			buttonInputItemProvider = new ButtonInputItemProvider(this);
		}

		return buttonInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosevents.ButtonInputAccumulator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonInputAccumulatorItemProvider buttonInputAccumulatorItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosevents.ButtonInputAccumulator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonInputAccumulatorAdapter() {
		if (buttonInputAccumulatorItemProvider == null) {
			buttonInputAccumulatorItemProvider = new ButtonInputAccumulatorItemProvider(this);
		}

		return buttonInputAccumulatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosevents.ButtonInputReleased} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonInputReleasedItemProvider buttonInputReleasedItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosevents.ButtonInputReleased}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonInputReleasedAdapter() {
		if (buttonInputReleasedItemProvider == null) {
			buttonInputReleasedItemProvider = new ButtonInputReleasedItemProvider(this);
		}

		return buttonInputReleasedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosevents.PulseInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PulseInputItemProvider pulseInputItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosevents.PulseInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPulseInputAdapter() {
		if (pulseInputItemProvider == null) {
			pulseInputItemProvider = new PulseInputItemProvider(this);
		}

		return pulseInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosevents.AnalogRead} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalogReadItemProvider analogReadItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosevents.AnalogRead}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalogReadAdapter() {
		if (analogReadItemProvider == null) {
			analogReadItemProvider = new AnalogReadItemProvider(this);
		}

		return analogReadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosevents.AnalogReadPerformOnHigh} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalogReadPerformOnHighItemProvider analogReadPerformOnHighItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosevents.AnalogReadPerformOnHigh}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalogReadPerformOnHighAdapter() {
		if (analogReadPerformOnHighItemProvider == null) {
			analogReadPerformOnHighItemProvider = new AnalogReadPerformOnHighItemProvider(this);
		}

		return analogReadPerformOnHighItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosevents.AnalogReadPerformOnLow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalogReadPerformOnLowItemProvider analogReadPerformOnLowItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosevents.AnalogReadPerformOnLow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalogReadPerformOnLowAdapter() {
		if (analogReadPerformOnLowItemProvider == null) {
			analogReadPerformOnLowItemProvider = new AnalogReadPerformOnLowItemProvider(this);
		}

		return analogReadPerformOnLowItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (interruptedItemProvider != null) interruptedItemProvider.dispose();
		if (buttonInputItemProvider != null) buttonInputItemProvider.dispose();
		if (buttonInputAccumulatorItemProvider != null) buttonInputAccumulatorItemProvider.dispose();
		if (buttonInputReleasedItemProvider != null) buttonInputReleasedItemProvider.dispose();
		if (pulseInputItemProvider != null) pulseInputItemProvider.dispose();
		if (analogReadItemProvider != null) analogReadItemProvider.dispose();
		if (analogReadPerformOnHighItemProvider != null) analogReadPerformOnHighItemProvider.dispose();
		if (analogReadPerformOnLowItemProvider != null) analogReadPerformOnLowItemProvider.dispose();
	}

}
