/**
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.scoping;

import es.udima.tfm.cesarlaso.scoping.AbstractIotDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class IotDslScopeProvider extends AbstractIotDslScopeProvider {
}
