/*
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.parser.antlr;

import com.google.inject.Inject;
import es.udima.tfm.cesarlaso.parser.antlr.internal.InternalIotDslParser;
import es.udima.tfm.cesarlaso.services.IotDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class IotDslParser extends AbstractAntlrParser {

	@Inject
	private IotDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIotDslParser createParser(XtextTokenStream stream) {
		return new InternalIotDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "IotProyect";
	}

	public IotDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IotDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
