/*
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IotDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("es/udima/tfm/cesarlaso/parser/antlr/internal/InternalIotDsl.tokens");
	}
}
