/**
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.ui;

import es.udima.tfm.cesarlaso.ui.AbstractIotDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IotDslUiModule extends AbstractIotDslUiModule {
  public IotDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
