/**
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.validation;

import es.udima.tfm.cesarlaso.validation.AbstractIotDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IotDslValidator extends AbstractIotDslValidator {
}
