/*
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.ui;

import com.google.inject.Injector;
import es.udima.cesarlaso.tfm.dsl2.ui.internal.Dsl2Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IotDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Dsl2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Dsl2Activator.getInstance().getInjector(Dsl2Activator.ES_UDIMA_TFM_CESARLASO_IOTDSL);
	}
	
}
