/**
 */
package es.udima.cesarlaso.tfm.gpiosactuators.provider;

import es.udima.cesarlaso.tfm.gpiosactuators.util.GpiosactuatorsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class GpiosactuatorsItemProviderAdapterFactory extends GpiosactuatorsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GpiosactuatorsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosactuators.ChangeOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChangeOutputItemProvider changeOutputItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosactuators.ChangeOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChangeOutputAdapter() {
		if (changeOutputItemProvider == null) {
			changeOutputItemProvider = new ChangeOutputItemProvider(this);
		}

		return changeOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosactuators.ButtonOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonOutputItemProvider buttonOutputItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosactuators.ButtonOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonOutputAdapter() {
		if (buttonOutputItemProvider == null) {
			buttonOutputItemProvider = new ButtonOutputItemProvider(this);
		}

		return buttonOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosactuators.PulseOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PulseOutputItemProvider pulseOutputItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosactuators.PulseOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPulseOutputAdapter() {
		if (pulseOutputItemProvider == null) {
			pulseOutputItemProvider = new PulseOutputItemProvider(this);
		}

		return pulseOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosactuators.BlinkOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlinkOutputItemProvider blinkOutputItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosactuators.BlinkOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlinkOutputAdapter() {
		if (blinkOutputItemProvider == null) {
			blinkOutputItemProvider = new BlinkOutputItemProvider(this);
		}

		return blinkOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosactuators.BlinkTimerOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlinkTimerOutputItemProvider blinkTimerOutputItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosactuators.BlinkTimerOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlinkTimerOutputAdapter() {
		if (blinkTimerOutputItemProvider == null) {
			blinkTimerOutputItemProvider = new BlinkTimerOutputItemProvider(this);
		}

		return blinkTimerOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosactuators.Pwm} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PwmItemProvider pwmItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosactuators.Pwm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPwmAdapter() {
		if (pwmItemProvider == null) {
			pwmItemProvider = new PwmItemProvider(this);
		}

		return pwmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.udima.cesarlaso.tfm.gpiosactuators.TransformTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransformToItemProvider transformToItemProvider;

	/**
	 * This creates an adapter for a {@link es.udima.cesarlaso.tfm.gpiosactuators.TransformTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransformToAdapter() {
		if (transformToItemProvider == null) {
			transformToItemProvider = new TransformToItemProvider(this);
		}

		return transformToItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (changeOutputItemProvider != null) changeOutputItemProvider.dispose();
		if (buttonOutputItemProvider != null) buttonOutputItemProvider.dispose();
		if (pulseOutputItemProvider != null) pulseOutputItemProvider.dispose();
		if (blinkOutputItemProvider != null) blinkOutputItemProvider.dispose();
		if (blinkTimerOutputItemProvider != null) blinkTimerOutputItemProvider.dispose();
		if (pwmItemProvider != null) pwmItemProvider.dispose();
		if (transformToItemProvider != null) transformToItemProvider.dispose();
	}

}
