/*
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractIotDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/iotproyects"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/deploymentdevices"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/servers"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/gpios"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/events"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/timers"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/communications/programs"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/programs"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/communications/events"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/gpios/events"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/operatingsystemactuators"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://tfm.cesarlaso.udima.es/gpios/actuators"));
		return result;
	}
	
}
