/*
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.ide.contentassist.antlr;

import com.google.inject.Inject;
import es.udima.tfm.cesarlaso.ide.contentassist.antlr.internal.InternalIotDslParser;
import es.udima.tfm.cesarlaso.services.IotDslGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class IotDslParser extends AbstractContentAssistParser {

	@Inject
	private IotDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalIotDslParser createParser() {
		InternalIotDslParser result = new InternalIotDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDeviceAccess().getAlternatives(), "rule__Device__Alternatives");
					put(grammarAccess.getPinAccess().getAlternatives(), "rule__Pin__Alternatives");
					put(grammarAccess.getEventAccess().getAlternatives(), "rule__Event__Alternatives");
					put(grammarAccess.getTimerAccess().getAlternatives(), "rule__Timer__Alternatives");
					put(grammarAccess.getActuatorAccess().getAlternatives(), "rule__Actuator__Alternatives");
					put(grammarAccess.getRemoteIdentifierAccess().getAlternatives(), "rule__RemoteIdentifier__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTimeUnitTypeAccess().getAlternatives(), "rule__TimeUnitType__Alternatives");
					put(grammarAccess.getResizeTypeAccess().getAlternatives(), "rule__ResizeType__Alternatives");
					put(grammarAccess.getPinResistorAccess().getAlternatives(), "rule__PinResistor__Alternatives");
					put(grammarAccess.getGpioInterruptModeAccess().getAlternatives(), "rule__GpioInterruptMode__Alternatives");
					put(grammarAccess.getDigitalPinStatusAccess().getAlternatives(), "rule__DigitalPinStatus__Alternatives");
					put(grammarAccess.getIotProyectAccess().getGroup(), "rule__IotProyect__Group__0");
					put(grammarAccess.getIotProyectAccess().getGroup_10(), "rule__IotProyect__Group_10__0");
					put(grammarAccess.getIotProyectAccess().getGroup_15(), "rule__IotProyect__Group_15__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getELongAccess().getGroup(), "rule__ELong__Group__0");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getProgramAccess().getGroup_2(), "rule__Program__Group_2__0");
					put(grammarAccess.getProgramAccess().getGroup_2_3(), "rule__Program__Group_2_3__0");
					put(grammarAccess.getProgramAccess().getGroup_3(), "rule__Program__Group_3__0");
					put(grammarAccess.getProgramAccess().getGroup_3_3(), "rule__Program__Group_3_3__0");
					put(grammarAccess.getProgramAccess().getGroup_4(), "rule__Program__Group_4__0");
					put(grammarAccess.getProgramAccess().getGroup_4_3(), "rule__Program__Group_4_3__0");
					put(grammarAccess.getProgramAccess().getGroup_10(), "rule__Program__Group_10__0");
					put(grammarAccess.getProgramStateAccess().getGroup(), "rule__ProgramState__Group__0");
					put(grammarAccess.getProgramStateAccess().getGroup_4(), "rule__ProgramState__Group_4__0");
					put(grammarAccess.getNetworkConnectedAccess().getGroup(), "rule__NetworkConnected__Group__0");
					put(grammarAccess.getNetworkConnectedAccess().getGroup_3(), "rule__NetworkConnected__Group_3__0");
					put(grammarAccess.getNetworkDisconnectedAccess().getGroup(), "rule__NetworkDisconnected__Group__0");
					put(grammarAccess.getNetworkDisconnectedAccess().getGroup_3(), "rule__NetworkDisconnected__Group_3__0");
					put(grammarAccess.getServerConnectedAccess().getGroup(), "rule__ServerConnected__Group__0");
					put(grammarAccess.getServerConnectedAccess().getGroup_3(), "rule__ServerConnected__Group_3__0");
					put(grammarAccess.getServerDisconnectedAccess().getGroup(), "rule__ServerDisconnected__Group__0");
					put(grammarAccess.getServerDisconnectedAccess().getGroup_3(), "rule__ServerDisconnected__Group_3__0");
					put(grammarAccess.getTimerEventAccess().getGroup(), "rule__TimerEvent__Group__0");
					put(grammarAccess.getTimerEventAccess().getGroup_5(), "rule__TimerEvent__Group_5__0");
					put(grammarAccess.getNowAccess().getGroup(), "rule__Now__Group__0");
					put(grammarAccess.getRepeatedAccess().getGroup(), "rule__Repeated__Group__0");
					put(grammarAccess.getClockAccess().getGroup(), "rule__Clock__Group__0");
					put(grammarAccess.getCronAccess().getGroup(), "rule__Cron__Group__0");
					put(grammarAccess.getGpioInterruptedAccess().getGroup(), "rule__GpioInterrupted__Group__0");
					put(grammarAccess.getGpioInterruptedAccess().getGroup_5(), "rule__GpioInterrupted__Group_5__0");
					put(grammarAccess.getGpioButtonInputAccess().getGroup(), "rule__GpioButtonInput__Group__0");
					put(grammarAccess.getGpioButtonInputAccess().getGroup_9(), "rule__GpioButtonInput__Group_9__0");
					put(grammarAccess.getGpioButtonInputAccumulatorAccess().getGroup(), "rule__GpioButtonInputAccumulator__Group__0");
					put(grammarAccess.getGpioButtonInputAccumulatorAccess().getGroup_11(), "rule__GpioButtonInputAccumulator__Group_11__0");
					put(grammarAccess.getGpioButtonReleasedAccess().getGroup(), "rule__GpioButtonReleased__Group__0");
					put(grammarAccess.getGpioButtonReleasedAccess().getGroup_7(), "rule__GpioButtonReleased__Group_7__0");
					put(grammarAccess.getGpioPulseInputAccess().getGroup(), "rule__GpioPulseInput__Group__0");
					put(grammarAccess.getGpioPulseInputAccess().getGroup_13(), "rule__GpioPulseInput__Group_13__0");
					put(grammarAccess.getGpioAnalogReadAccess().getGroup(), "rule__GpioAnalogRead__Group__0");
					put(grammarAccess.getGpioAnalogReadAccess().getGroup_7(), "rule__GpioAnalogRead__Group_7__0");
					put(grammarAccess.getGpioAnalogReadPerformOnHighAccess().getGroup(), "rule__GpioAnalogReadPerformOnHigh__Group__0");
					put(grammarAccess.getGpioAnalogReadPerformOnHighAccess().getGroup_9(), "rule__GpioAnalogReadPerformOnHigh__Group_9__0");
					put(grammarAccess.getGpioAnalogReadPerformOnLowAccess().getGroup(), "rule__GpioAnalogReadPerformOnLow__Group__0");
					put(grammarAccess.getGpioAnalogReadPerformOnLowAccess().getGroup_9(), "rule__GpioAnalogReadPerformOnLow__Group_9__0");
					put(grammarAccess.getTimeAccess().getGroup(), "rule__Time__Group__0");
					put(grammarAccess.getTimeUnitValueAccess().getGroup(), "rule__TimeUnitValue__Group__0");
					put(grammarAccess.getFilePathAccess().getGroup(), "rule__FilePath__Group__0");
					put(grammarAccess.getRemoteEventAccess().getGroup(), "rule__RemoteEvent__Group__0");
					put(grammarAccess.getRemoteEventAccess().getGroup_4(), "rule__RemoteEvent__Group_4__0");
					put(grammarAccess.getRemoteActuatorAccess().getGroup(), "rule__RemoteActuator__Group__0");
					put(grammarAccess.getSystemCommandAccess().getGroup(), "rule__SystemCommand__Group__0");
					put(grammarAccess.getDownloadAccess().getGroup(), "rule__Download__Group__0");
					put(grammarAccess.getPlaySoundAccess().getGroup(), "rule__PlaySound__Group__0");
					put(grammarAccess.getPlaySoundAccess().getGroup_1(), "rule__PlaySound__Group_1__0");
					put(grammarAccess.getBackgroundImageAccess().getGroup(), "rule__BackgroundImage__Group__0");
					put(grammarAccess.getDrawImageAccess().getGroup(), "rule__DrawImage__Group__0");
					put(grammarAccess.getPlayVideoAccess().getGroup(), "rule__PlayVideo__Group__0");
					put(grammarAccess.getChangeStateActuatorAccess().getGroup(), "rule__ChangeStateActuator__Group__0");
					put(grammarAccess.getDigitalInputPinAccess().getGroup(), "rule__DigitalInputPin__Group__0");
					put(grammarAccess.getDigitalOutputPinAccess().getGroup(), "rule__DigitalOutputPin__Group__0");
					put(grammarAccess.getAnalogInputPinAccess().getGroup(), "rule__AnalogInputPin__Group__0");
					put(grammarAccess.getAnalogOutputPinAccess().getGroup(), "rule__AnalogOutputPin__Group__0");
					put(grammarAccess.getRemoteEventIdentifierAccess().getGroup(), "rule__RemoteEventIdentifier__Group__0");
					put(grammarAccess.getRemoteActuatorIdentifierAccess().getGroup(), "rule__RemoteActuatorIdentifier__Group__0");
					put(grammarAccess.getSequentialActuatorsAccess().getGroup(), "rule__SequentialActuators__Group__0");
					put(grammarAccess.getSequentialActuatorsAccess().getGroup_3(), "rule__SequentialActuators__Group_3__0");
					put(grammarAccess.getChangeOutputAccess().getGroup(), "rule__ChangeOutput__Group__0");
					put(grammarAccess.getButtonOutputAccess().getGroup(), "rule__ButtonOutput__Group__0");
					put(grammarAccess.getPulseOutputAccess().getGroup(), "rule__PulseOutput__Group__0");
					put(grammarAccess.getBlinkOutputAccess().getGroup(), "rule__BlinkOutput__Group__0");
					put(grammarAccess.getBlinkTimerOutputAccess().getGroup(), "rule__BlinkTimerOutput__Group__0");
					put(grammarAccess.getPwmAccess().getGroup(), "rule__Pwm__Group__0");
					put(grammarAccess.getTransformToAccess().getGroup(), "rule__TransformTo__Group__0");
					put(grammarAccess.getWifiConfigurationAccess().getGroup(), "rule__WifiConfiguration__Group__0");
					put(grammarAccess.getSimulatorAccess().getGroup(), "rule__Simulator__Group__0");
					put(grammarAccess.getRaspberryAccess().getGroup(), "rule__Raspberry__Group__0");
					put(grammarAccess.getRaspberryAccess().getGroup_2(), "rule__Raspberry__Group_2__0");
					put(grammarAccess.getBeagleboneAccess().getGroup(), "rule__Beaglebone__Group__0");
					put(grammarAccess.getBeagleboneAccess().getGroup_2(), "rule__Beaglebone__Group_2__0");
					put(grammarAccess.getESP8266Access().getGroup(), "rule__ESP8266__Group__0");
					put(grammarAccess.getESP8266Access().getGroup_2(), "rule__ESP8266__Group_2__0");
					put(grammarAccess.getJavaServerAccess().getGroup(), "rule__JavaServer__Group__0");
					put(grammarAccess.getIotProyectAccess().getNameAssignment_1(), "rule__IotProyect__NameAssignment_1");
					put(grammarAccess.getIotProyectAccess().getProductCodeAssignment_4(), "rule__IotProyect__ProductCodeAssignment_4");
					put(grammarAccess.getIotProyectAccess().getVersionAssignment_6(), "rule__IotProyect__VersionAssignment_6");
					put(grammarAccess.getIotProyectAccess().getDeploymentDeviceAssignment_9(), "rule__IotProyect__DeploymentDeviceAssignment_9");
					put(grammarAccess.getIotProyectAccess().getDeploymentDeviceAssignment_10_1(), "rule__IotProyect__DeploymentDeviceAssignment_10_1");
					put(grammarAccess.getIotProyectAccess().getServerAssignment_14(), "rule__IotProyect__ServerAssignment_14");
					put(grammarAccess.getIotProyectAccess().getServerAssignment_15_1(), "rule__IotProyect__ServerAssignment_15_1");
					put(grammarAccess.getIotProyectAccess().getProgramAssignment_17(), "rule__IotProyect__ProgramAssignment_17");
					put(grammarAccess.getProgramAccess().getGpioAliasesAssignment_2_2(), "rule__Program__GpioAliasesAssignment_2_2");
					put(grammarAccess.getProgramAccess().getGpioAliasesAssignment_2_3_1(), "rule__Program__GpioAliasesAssignment_2_3_1");
					put(grammarAccess.getProgramAccess().getRemoteIdentifiersAssignment_3_2(), "rule__Program__RemoteIdentifiersAssignment_3_2");
					put(grammarAccess.getProgramAccess().getRemoteIdentifiersAssignment_3_3_1(), "rule__Program__RemoteIdentifiersAssignment_3_3_1");
					put(grammarAccess.getProgramAccess().getFilesAssignment_4_2(), "rule__Program__FilesAssignment_4_2");
					put(grammarAccess.getProgramAccess().getFilesAssignment_4_3_1(), "rule__Program__FilesAssignment_4_3_1");
					put(grammarAccess.getProgramAccess().getStateAssignment_6(), "rule__Program__StateAssignment_6");
					put(grammarAccess.getProgramAccess().getStatesAssignment_9(), "rule__Program__StatesAssignment_9");
					put(grammarAccess.getProgramAccess().getStatesAssignment_10_1(), "rule__Program__StatesAssignment_10_1");
					put(grammarAccess.getProgramStateAccess().getNameAssignment_1(), "rule__ProgramState__NameAssignment_1");
					put(grammarAccess.getProgramStateAccess().getEventsAssignment_3(), "rule__ProgramState__EventsAssignment_3");
					put(grammarAccess.getProgramStateAccess().getEventsAssignment_4_1(), "rule__ProgramState__EventsAssignment_4_1");
					put(grammarAccess.getNetworkConnectedAccess().getActuatorsAssignment_2(), "rule__NetworkConnected__ActuatorsAssignment_2");
					put(grammarAccess.getNetworkConnectedAccess().getActuatorsAssignment_3_1(), "rule__NetworkConnected__ActuatorsAssignment_3_1");
					put(grammarAccess.getNetworkDisconnectedAccess().getActuatorsAssignment_2(), "rule__NetworkDisconnected__ActuatorsAssignment_2");
					put(grammarAccess.getNetworkDisconnectedAccess().getActuatorsAssignment_3_1(), "rule__NetworkDisconnected__ActuatorsAssignment_3_1");
					put(grammarAccess.getServerConnectedAccess().getActuatorsAssignment_2(), "rule__ServerConnected__ActuatorsAssignment_2");
					put(grammarAccess.getServerConnectedAccess().getActuatorsAssignment_3_1(), "rule__ServerConnected__ActuatorsAssignment_3_1");
					put(grammarAccess.getServerDisconnectedAccess().getActuatorsAssignment_2(), "rule__ServerDisconnected__ActuatorsAssignment_2");
					put(grammarAccess.getServerDisconnectedAccess().getActuatorsAssignment_3_1(), "rule__ServerDisconnected__ActuatorsAssignment_3_1");
					put(grammarAccess.getTimerEventAccess().getTimerAssignment_2(), "rule__TimerEvent__TimerAssignment_2");
					put(grammarAccess.getTimerEventAccess().getActuatorsAssignment_4(), "rule__TimerEvent__ActuatorsAssignment_4");
					put(grammarAccess.getTimerEventAccess().getActuatorsAssignment_5_1(), "rule__TimerEvent__ActuatorsAssignment_5_1");
					put(grammarAccess.getRepeatedAccess().getValueAssignment_1(), "rule__Repeated__ValueAssignment_1");
					put(grammarAccess.getClockAccess().getValueAssignment_1(), "rule__Clock__ValueAssignment_1");
					put(grammarAccess.getCronAccess().getValueAssignment_1(), "rule__Cron__ValueAssignment_1");
					put(grammarAccess.getGpioInterruptedAccess().getPinAssignment_1(), "rule__GpioInterrupted__PinAssignment_1");
					put(grammarAccess.getGpioInterruptedAccess().getModeAssignment_2(), "rule__GpioInterrupted__ModeAssignment_2");
					put(grammarAccess.getGpioInterruptedAccess().getActuatorsAssignment_4(), "rule__GpioInterrupted__ActuatorsAssignment_4");
					put(grammarAccess.getGpioInterruptedAccess().getActuatorsAssignment_5_1(), "rule__GpioInterrupted__ActuatorsAssignment_5_1");
					put(grammarAccess.getGpioButtonInputAccess().getPinAssignment_1(), "rule__GpioButtonInput__PinAssignment_1");
					put(grammarAccess.getGpioButtonInputAccess().getModeAssignment_4(), "rule__GpioButtonInput__ModeAssignment_4");
					put(grammarAccess.getGpioButtonInputAccess().getMinDurationAssignment_6(), "rule__GpioButtonInput__MinDurationAssignment_6");
					put(grammarAccess.getGpioButtonInputAccess().getActuatorsAssignment_8(), "rule__GpioButtonInput__ActuatorsAssignment_8");
					put(grammarAccess.getGpioButtonInputAccess().getActuatorsAssignment_9_1(), "rule__GpioButtonInput__ActuatorsAssignment_9_1");
					put(grammarAccess.getGpioButtonInputAccumulatorAccess().getPinAssignment_1(), "rule__GpioButtonInputAccumulator__PinAssignment_1");
					put(grammarAccess.getGpioButtonInputAccumulatorAccess().getModeAssignment_4(), "rule__GpioButtonInputAccumulator__ModeAssignment_4");
					put(grammarAccess.getGpioButtonInputAccumulatorAccess().getMinDurationAssignment_6(), "rule__GpioButtonInputAccumulator__MinDurationAssignment_6");
					put(grammarAccess.getGpioButtonInputAccumulatorAccess().getCountAssignment_8(), "rule__GpioButtonInputAccumulator__CountAssignment_8");
					put(grammarAccess.getGpioButtonInputAccumulatorAccess().getActuatorsAssignment_10(), "rule__GpioButtonInputAccumulator__ActuatorsAssignment_10");
					put(grammarAccess.getGpioButtonInputAccumulatorAccess().getActuatorsAssignment_11_1(), "rule__GpioButtonInputAccumulator__ActuatorsAssignment_11_1");
					put(grammarAccess.getGpioButtonReleasedAccess().getPinAssignment_1(), "rule__GpioButtonReleased__PinAssignment_1");
					put(grammarAccess.getGpioButtonReleasedAccess().getModeAssignment_4(), "rule__GpioButtonReleased__ModeAssignment_4");
					put(grammarAccess.getGpioButtonReleasedAccess().getActuatorsAssignment_6(), "rule__GpioButtonReleased__ActuatorsAssignment_6");
					put(grammarAccess.getGpioButtonReleasedAccess().getActuatorsAssignment_7_1(), "rule__GpioButtonReleased__ActuatorsAssignment_7_1");
					put(grammarAccess.getGpioPulseInputAccess().getPinAssignment_1(), "rule__GpioPulseInput__PinAssignment_1");
					put(grammarAccess.getGpioPulseInputAccess().getModeAssignment_4(), "rule__GpioPulseInput__ModeAssignment_4");
					put(grammarAccess.getGpioPulseInputAccess().getCountAssignment_6(), "rule__GpioPulseInput__CountAssignment_6");
					put(grammarAccess.getGpioPulseInputAccess().getWidthAssignment_8(), "rule__GpioPulseInput__WidthAssignment_8");
					put(grammarAccess.getGpioPulseInputAccess().getSpaceWidthAssignment_10(), "rule__GpioPulseInput__SpaceWidthAssignment_10");
					put(grammarAccess.getGpioPulseInputAccess().getActuatorsAssignment_12(), "rule__GpioPulseInput__ActuatorsAssignment_12");
					put(grammarAccess.getGpioPulseInputAccess().getActuatorsAssignment_13_1(), "rule__GpioPulseInput__ActuatorsAssignment_13_1");
					put(grammarAccess.getGpioAnalogReadAccess().getPinAssignment_1(), "rule__GpioAnalogRead__PinAssignment_1");
					put(grammarAccess.getGpioAnalogReadAccess().getPollIntervalLoopsAssignment_3(), "rule__GpioAnalogRead__PollIntervalLoopsAssignment_3");
					put(grammarAccess.getGpioAnalogReadAccess().getActuatorsAssignment_6(), "rule__GpioAnalogRead__ActuatorsAssignment_6");
					put(grammarAccess.getGpioAnalogReadAccess().getActuatorsAssignment_7_1(), "rule__GpioAnalogRead__ActuatorsAssignment_7_1");
					put(grammarAccess.getGpioAnalogReadPerformOnHighAccess().getPinAssignment_1(), "rule__GpioAnalogReadPerformOnHigh__PinAssignment_1");
					put(grammarAccess.getGpioAnalogReadPerformOnHighAccess().getPollIntervalLoopsAssignment_3(), "rule__GpioAnalogReadPerformOnHigh__PollIntervalLoopsAssignment_3");
					put(grammarAccess.getGpioAnalogReadPerformOnHighAccess().getValueAssignment_6(), "rule__GpioAnalogReadPerformOnHigh__ValueAssignment_6");
					put(grammarAccess.getGpioAnalogReadPerformOnHighAccess().getActuatorsAssignment_8(), "rule__GpioAnalogReadPerformOnHigh__ActuatorsAssignment_8");
					put(grammarAccess.getGpioAnalogReadPerformOnHighAccess().getActuatorsAssignment_9_1(), "rule__GpioAnalogReadPerformOnHigh__ActuatorsAssignment_9_1");
					put(grammarAccess.getGpioAnalogReadPerformOnLowAccess().getPinAssignment_1(), "rule__GpioAnalogReadPerformOnLow__PinAssignment_1");
					put(grammarAccess.getGpioAnalogReadPerformOnLowAccess().getPollIntervalLoopsAssignment_3(), "rule__GpioAnalogReadPerformOnLow__PollIntervalLoopsAssignment_3");
					put(grammarAccess.getGpioAnalogReadPerformOnLowAccess().getValueAssignment_6(), "rule__GpioAnalogReadPerformOnLow__ValueAssignment_6");
					put(grammarAccess.getGpioAnalogReadPerformOnLowAccess().getActuatorsAssignment_8(), "rule__GpioAnalogReadPerformOnLow__ActuatorsAssignment_8");
					put(grammarAccess.getGpioAnalogReadPerformOnLowAccess().getActuatorsAssignment_9_1(), "rule__GpioAnalogReadPerformOnLow__ActuatorsAssignment_9_1");
					put(grammarAccess.getTimeAccess().getHourAssignment_0(), "rule__Time__HourAssignment_0");
					put(grammarAccess.getTimeAccess().getMinuteAssignment_2(), "rule__Time__MinuteAssignment_2");
					put(grammarAccess.getTimeAccess().getSecondAssignment_4(), "rule__Time__SecondAssignment_4");
					put(grammarAccess.getTimeUnitValueAccess().getValueAssignment_0(), "rule__TimeUnitValue__ValueAssignment_0");
					put(grammarAccess.getTimeUnitValueAccess().getUnitAssignment_1(), "rule__TimeUnitValue__UnitAssignment_1");
					put(grammarAccess.getFilePathAccess().getNameAssignment_1(), "rule__FilePath__NameAssignment_1");
					put(grammarAccess.getFilePathAccess().getFilePathAssignment_3(), "rule__FilePath__FilePathAssignment_3");
					put(grammarAccess.getRemoteEventAccess().getIdentifierAssignment_1(), "rule__RemoteEvent__IdentifierAssignment_1");
					put(grammarAccess.getRemoteEventAccess().getActuatorsAssignment_3(), "rule__RemoteEvent__ActuatorsAssignment_3");
					put(grammarAccess.getRemoteEventAccess().getActuatorsAssignment_4_1(), "rule__RemoteEvent__ActuatorsAssignment_4_1");
					put(grammarAccess.getRemoteActuatorAccess().getIdentifierAssignment_1(), "rule__RemoteActuator__IdentifierAssignment_1");
					put(grammarAccess.getSystemCommandAccess().getFilePathAssignment_1(), "rule__SystemCommand__FilePathAssignment_1");
					put(grammarAccess.getDownloadAccess().getUrlAssignment_1(), "rule__Download__UrlAssignment_1");
					put(grammarAccess.getDownloadAccess().getFilePathAssignment_3(), "rule__Download__FilePathAssignment_3");
					put(grammarAccess.getPlaySoundAccess().getVolumeAssignment_1_1(), "rule__PlaySound__VolumeAssignment_1_1");
					put(grammarAccess.getPlaySoundAccess().getFilePathAssignment_2(), "rule__PlaySound__FilePathAssignment_2");
					put(grammarAccess.getBackgroundImageAccess().getFilePathAssignment_1(), "rule__BackgroundImage__FilePathAssignment_1");
					put(grammarAccess.getBackgroundImageAccess().getResizeTypeAssignment_2(), "rule__BackgroundImage__ResizeTypeAssignment_2");
					put(grammarAccess.getDrawImageAccess().getFilePathAssignment_1(), "rule__DrawImage__FilePathAssignment_1");
					put(grammarAccess.getDrawImageAccess().getPositionXAssignment_4(), "rule__DrawImage__PositionXAssignment_4");
					put(grammarAccess.getDrawImageAccess().getPositionYAssignment_6(), "rule__DrawImage__PositionYAssignment_6");
					put(grammarAccess.getDrawImageAccess().getPositionZAssignment_8(), "rule__DrawImage__PositionZAssignment_8");
					put(grammarAccess.getDrawImageAccess().getColorAssignment_10(), "rule__DrawImage__ColorAssignment_10");
					put(grammarAccess.getDrawImageAccess().getResizeTypeAssignment_12(), "rule__DrawImage__ResizeTypeAssignment_12");
					put(grammarAccess.getPlayVideoAccess().getFilePathAssignment_1(), "rule__PlayVideo__FilePathAssignment_1");
					put(grammarAccess.getPlayVideoAccess().getPositionXAssignment_4(), "rule__PlayVideo__PositionXAssignment_4");
					put(grammarAccess.getPlayVideoAccess().getPositionYAssignment_6(), "rule__PlayVideo__PositionYAssignment_6");
					put(grammarAccess.getPlayVideoAccess().getPositionZAssignment_8(), "rule__PlayVideo__PositionZAssignment_8");
					put(grammarAccess.getPlayVideoAccess().getColorAssignment_10(), "rule__PlayVideo__ColorAssignment_10");
					put(grammarAccess.getPlayVideoAccess().getResizeTypeAssignment_12(), "rule__PlayVideo__ResizeTypeAssignment_12");
					put(grammarAccess.getChangeStateActuatorAccess().getStateAssignment_1(), "rule__ChangeStateActuator__StateAssignment_1");
					put(grammarAccess.getDigitalInputPinAccess().getNameAssignment_1(), "rule__DigitalInputPin__NameAssignment_1");
					put(grammarAccess.getDigitalInputPinAccess().getNumberAssignment_3(), "rule__DigitalInputPin__NumberAssignment_3");
					put(grammarAccess.getDigitalOutputPinAccess().getNameAssignment_1(), "rule__DigitalOutputPin__NameAssignment_1");
					put(grammarAccess.getDigitalOutputPinAccess().getNumberAssignment_3(), "rule__DigitalOutputPin__NumberAssignment_3");
					put(grammarAccess.getAnalogInputPinAccess().getNameAssignment_1(), "rule__AnalogInputPin__NameAssignment_1");
					put(grammarAccess.getAnalogInputPinAccess().getNumberAssignment_3(), "rule__AnalogInputPin__NumberAssignment_3");
					put(grammarAccess.getAnalogOutputPinAccess().getNameAssignment_1(), "rule__AnalogOutputPin__NameAssignment_1");
					put(grammarAccess.getAnalogOutputPinAccess().getNumberAssignment_3(), "rule__AnalogOutputPin__NumberAssignment_3");
					put(grammarAccess.getRemoteEventIdentifierAccess().getNameAssignment_1(), "rule__RemoteEventIdentifier__NameAssignment_1");
					put(grammarAccess.getRemoteActuatorIdentifierAccess().getNameAssignment_1(), "rule__RemoteActuatorIdentifier__NameAssignment_1");
					put(grammarAccess.getSequentialActuatorsAccess().getActuatorsAssignment_2(), "rule__SequentialActuators__ActuatorsAssignment_2");
					put(grammarAccess.getSequentialActuatorsAccess().getActuatorsAssignment_3_1(), "rule__SequentialActuators__ActuatorsAssignment_3_1");
					put(grammarAccess.getChangeOutputAccess().getPinAssignment_1(), "rule__ChangeOutput__PinAssignment_1");
					put(grammarAccess.getChangeOutputAccess().getStatusAssignment_2(), "rule__ChangeOutput__StatusAssignment_2");
					put(grammarAccess.getButtonOutputAccess().getPinAssignment_1(), "rule__ButtonOutput__PinAssignment_1");
					put(grammarAccess.getButtonOutputAccess().getDurationAssignment_3(), "rule__ButtonOutput__DurationAssignment_3");
					put(grammarAccess.getPulseOutputAccess().getPinAssignment_1(), "rule__PulseOutput__PinAssignment_1");
					put(grammarAccess.getPulseOutputAccess().getCountAssignment_4(), "rule__PulseOutput__CountAssignment_4");
					put(grammarAccess.getPulseOutputAccess().getWidthAssignment_6(), "rule__PulseOutput__WidthAssignment_6");
					put(grammarAccess.getPulseOutputAccess().getSpaceWidthAssignment_9(), "rule__PulseOutput__SpaceWidthAssignment_9");
					put(grammarAccess.getBlinkOutputAccess().getPinAssignment_1(), "rule__BlinkOutput__PinAssignment_1");
					put(grammarAccess.getBlinkOutputAccess().getIntervalAssignment_3(), "rule__BlinkOutput__IntervalAssignment_3");
					put(grammarAccess.getBlinkTimerOutputAccess().getPinAssignment_1(), "rule__BlinkTimerOutput__PinAssignment_1");
					put(grammarAccess.getBlinkTimerOutputAccess().getDurationAssignment_4(), "rule__BlinkTimerOutput__DurationAssignment_4");
					put(grammarAccess.getBlinkTimerOutputAccess().getIntervalAssignment_6(), "rule__BlinkTimerOutput__IntervalAssignment_6");
					put(grammarAccess.getPwmAccess().getPinAssignment_1(), "rule__Pwm__PinAssignment_1");
					put(grammarAccess.getPwmAccess().getValueAssignment_4(), "rule__Pwm__ValueAssignment_4");
					put(grammarAccess.getTransformToAccess().getPinAssignment_1(), "rule__TransformTo__PinAssignment_1");
					put(grammarAccess.getTransformToAccess().getValueAssignment_4(), "rule__TransformTo__ValueAssignment_4");
					put(grammarAccess.getTransformToAccess().getDurationAssignment_6(), "rule__TransformTo__DurationAssignment_6");
					put(grammarAccess.getWifiConfigurationAccess().getSsidAssignment_1(), "rule__WifiConfiguration__SsidAssignment_1");
					put(grammarAccess.getWifiConfigurationAccess().getPasswordAssignment_3(), "rule__WifiConfiguration__PasswordAssignment_3");
					put(grammarAccess.getRaspberryAccess().getWifiConfigurationAssignment_2_1(), "rule__Raspberry__WifiConfigurationAssignment_2_1");
					put(grammarAccess.getBeagleboneAccess().getWifiConfigurationAssignment_2_1(), "rule__Beaglebone__WifiConfigurationAssignment_2_1");
					put(grammarAccess.getESP8266Access().getWifiConfigurationAssignment_2_1(), "rule__ESP8266__WifiConfigurationAssignment_2_1");
					put(grammarAccess.getJavaServerAccess().getNetworkInterfaceAddressAssignment_3(), "rule__JavaServer__NetworkInterfaceAddressAssignment_3");
					put(grammarAccess.getJavaServerAccess().getNetworkInterfacePortAssignment_5(), "rule__JavaServer__NetworkInterfacePortAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public IotDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IotDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
