/*
 * generated by Xtext 2.12.0
 */
package es.udima.tfm.cesarlaso.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIotDslScopeProvider extends DelegatingScopeProvider {
}
